package:
  name: datadog-cpp
  version: 1.3.2
  epoch: 0
  description: "Datadog OpenTracing C++ Client"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - '@local packages'
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - curl
      - curl-dev
      - opentracing-cpp
      - msgpack

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/DataDog/dd-opentracing-cpp/archive/v${{package.version}}.tar.gz
      expected-sha256: 586f92166018cc27080d34e17c59d68219b85af745edf3cc9fe41403fc9b4ac6
      strip-components: 1

  - name: 'Configure DATADOG_CPP'
    runs: |
      cmake -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTING=OFF \
      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true .

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: false
