package:
  name: jaeger-cpp
  version: 0.7.0
  epoch: 0
  description: "Jaeger SDK with OpenTracing API for C++ binding."
  copyright:
    - license: MIT
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - yaml-cpp
      - yaml-cpp-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/jaegertracing/jaeger-client-cpp/archive/v${{package.version}}.tar.gz
      expected-sha256: 3a3a03060bf5e3fef52c9a2de02e6035cb557f389453d8f3b0c1d3d570636994
      strip-components: 1

  - name: 'Configure Jaeger'
    runs: |
      mkdir -p ${{targets.destdir}}/etc/nginx

      # build jaeger lib
      sed -i 's/-Werror/-Wno-psabi/' CMakeLists.txt
      # use the above built yaml-cpp instead until a new version of jaeger-client-cpp fixes the yaml-cpp issue
      # tl;dr new hunter is needed for new yaml-cpp, but new hunter has a conflict with old Thrift and new Boost
      sed -i 's/hunter_add_package(yaml-cpp)/#hunter_add_package(yaml-cpp)/' CMakeLists.txt
      sed -i 's/yaml-cpp::yaml-cpp/yaml-cpp/' CMakeLists.txt

      cat <<EOF > export.map
      {
        global:
          OpenTracingMakeTracerFactory;
          local: *;
      };
      EOF

  - uses: cmake/configure
    with:
      opt: |
        -DHUNTER_STATUS_DEBUG=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=${{targets.destdir}} \
        -DBUILD_TESTING=OFF \
        -DJAEGERTRACING_BUILD_EXAMPLES=OFF \
        -DJAEGERTRACING_BUILD_CROSSDOCK=OFF \
        -DJAEGERTRACING_COVERAGE=OFF \
        -DJAEGERTRACING_PLUGIN=ON \
        -DHUNTER_CONFIGURATION_TYPES=Release \
        -DBUILD_SHARED_LIBS=OFF \
        -DJAEGERTRACING_WITH_YAML_CPP=ON \
        -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true

  - uses: cmake/build

  - uses: cmake/install

update:
  enabled: false
