package:
  name: libsrt
  version: 1.5.1
  epoch: 0
  description: "Secure Reliable Transport (SRT)"
  copyright:
    - license: MPL-2.0

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - openssl
      - openssl-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/Haivision/srt/archive/v${{package.version}}.tar.gz
      expected-sha512: f3aa1f7773540e2dd31cd19b124eec3c3d830f59c08d953cae01e129a58db7e639bdf94c8a5a678435ae9a1d2402e2c77196fc9c4e75b42aa37d8eafcc16f436

  - uses: cmake/configure
    with:
      opts: |
        -DUSE_ENCLIB=openssl-evp \
        -DENABLE_STATIC=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

update:
  enabled: false
