package:
  name: lua-resty-cache
  version: 0.11
  epoch: 0
  description: "lua-resty-lrucache - Lua-land LRU cache based on the LuaJIT FFI."
  copyright:
    - license: BSD
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-resty-lrucache/archive/v${{package.version}}.tar.gz
      expected-sha256: e810ed124fe788b8e4aac2c8960dda1b9a6f8d0ca94ce162f28d3f4d877df8af
      strip-components: 1

  - uses: autoconf/make-install

update:
  enabled: false
