package:
  name: lua-resty-string
  version: 0.15
  epoch: 0
  description: "String utilities and common hash functions for ngx_lua and LuaJIT"
  copyright:
    - license: BSD
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-resty-string/archive/v${{package.version}}.tar.gz
      expected-sha256: bdbf271003d95aa91cab0a92f24dca129e99b33f79c13ebfcdbbcbb558129491

  - runs: |
      make DESTDIR="${{targets.destdir}}" install

update:
  enabled: false
