package:
  name: lua-resty-dns
  version: 0.22
  epoch: 0
  description: "lua-resty-lrucache - Lua-land LRU cache based on the LuaJIT FFI."
  copyright:
    - license: BSD
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-resty-dns/archive/v${{package.version}}.tar.gz
      expected-sha256: 70e9a01eb32ccade0d5116a25bcffde0445b94ad35035ce06b94ccd260ad1bf0
      strip-components: 1

  - uses: autoconf/make-install

update:
  enabled: false
