package:
  name: lua-resty-global-throttle
  version: 0.2.0
  epoch: 0
  description: "lua-resty-dns - Lua DNS resolver for the ngx_lua based on the cosocket API"
  copyright:
    - license: BSD
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/ElvinEfendi/lua-resty-global-throttle/archive/v${{package.version}}.tar.gz
      expected-sha256: 0fb790e394510e73fdba1492e576aaec0b8ee9ef08e3e821ce253a07719cf7ea
      strip-components: 1

  - uses: autoconf/make-install

update:
  enabled: false
