package:
  name: lua-resty-ipmatcher
  version: 0.6.1
  epoch: 0
  description: "High-performance match IP address for Nginx + Lua"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - luajit

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/api7/lua-resty-ipmatcher/archive/v${{package.version}}.tar.gz
      expected-sha256: efb767487ea3f6031577b9b224467ddbda2ad51a41c5867a47582d4ad85d609e
      strip-components: 1

  - name: "Configure lua-resty-ipmatcher"
    runs: |
      export INST_LUADIR=/usr/local/lib/lua
      make DESTDIR="${{targets.destdir}}" install

update:
  enabled: false
