package:
  name: lua-resty-cookie
  version: 0.0_git20200824
  epoch: 0
  description: "lua-resty-lrucache - Lua-land LRU cache based on the LuaJIT FFI."
  copyright:
    - license: BSD
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/cloudflare/lua-resty-cookie/archive/303e32e512defced053a6484bc0745cf9dc0d39e.tar.gz
      expected-sha256: 5ed48c36231e2622b001308622d46a0077525ac2f751e8cc0c9905914254baa4
      strip-components: 1

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: false
