package:
  name: lua-resty-balancer
  version: 0.04
  epoch: 0
  description: "A generic consistent hash implementation for OpenResty/Lua"
  copyright:
    - license: BSD
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-resty-balancer/archive/v${{package.version}}.tar.gz
      expected-sha256: 16d72ed133f0c6df376a327386c3ef4e9406cf51003a700737c3805770ade7c5
      strip-components: 1

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: false
