package:
  name: lua-resty-memcached
  version: 0.16
  epoch: 0
  description: "Lua memcached client driver for the ngx_lua based on the cosocket API"
  copyright:
    - license: BSD
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-resty-memcached/archive/v${{package.version}}.tar.gz
      expected-sha256: 42893da0e3de4ec180c9bf02f82608d78787290a70c5644b538f29d243147396
      strip-components: 1

  - uses: autoconf/make-install

update:
  enabled: false
