package:
  name: lua-cjson
  version: 0.0_git20210708
  epoch: 0
  description: "Lua CJSON is a fast JSON encoding/parsing module for Lua"
  copyright:
    - license: MIT
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle
      - luajit

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-cjson/archive/4b350c531de3d71008c77ae94e59275b8371b4dc.tar.gz
      expected-sha256: 8d602af2669fb386931760916a39f6c9034f2363c4965f215042c086b8215238
      strip-components: 1

  - name: "Configure"
    runs: |
      export LUAJIT_LIB=/usr/local/lib
      export LUA_LIB_DIR="$LUAJIT_LIB/lua"
      export LUAJIT_INC=/usr/local/include/luajit-2.1

      ln -s /usr/local/bin/luajit /usr/local/bin/lua
      ln -s "$LUAJIT_INC" /usr/local/include/lua

      export LUA_INCLUDE_DIR=/usr/local/include/luajit-2.1
      ln -s $LUA_INCLUDE_DIR /usr/include/lua5.1
      ls -lah /usr/local/lib
      make
      make DESTDIR="${{targets.destdir}}" install

update:
  enabled: false
