package:
  name: lua-cjson
  version: 2.1.0.10
  epoch: 0
  description: "Lua CJSON is a fast JSON encoding/parsing module for Lua"
  copyright:
    - license: MIT
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle
      - luajit
      - luajit-dev

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/openresty/lua-cjson/archive/${{package.version}}.tar.gz
      expected-sha256: 0c551d6898f89f876e48730f9b55790d0ba07d5bc0aa6c76153277f63c19489f
      strip-components: 1

  - name: "Configure"
    runs: |
      export LUAJIT_LIB=/usr/local/lib
      export LUA_LIB_DIR="$LUAJIT_LIB/lua"
      export LUAJIT_INC=/usr/local/include/luajit-2.1

      ln -s /usr/local/bin/luajit /usr/local/bin/lua
      ln -s "$LUAJIT_INC" /usr/local/include/lua

       export LUA_INCLUDE_DIR=/usr/local/include/luajit-2.1
       ln -s $LUA_INCLUDE_DIR /usr/include/lua5.1

       make all

       make DESTDIR="${{targets.destdir}}" install

update:
  enabled: false
