package:
  name: luajit
  version: 2.1_p20210510
  epoch: 1
  description: OpenResty's branch of LuaJIT
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf

pipeline:
  - uses: fetch
    with:
      expected-sha256: 1ee6dad809a5bb22efb45e6dac767f7ce544ad652d353a93d7f26b605f69fe3f
      uri: https://github.com/openresty/luajit2/archive/v2.1-20210510/luajit${{package.version}}.tar.gz

  - runs: |
      export LUAJIT_LIB=${{targets.destdir}}/usr/local/lib
      export LUA_LIB_DIR="$LUAJIT_LIB/lua"
      export LUAJIT_INC=${{targets.destdir}}/usr/local/include/luajit-2.1

      make CCDEBUG=-g
      make DESTDIR="${{targets.destdir}}" install

      ln -s ${{targets.destdir}}/usr/local/bin/luajit ${{targets.destdir}}/usr/local/bin/lua
      ln -s "$LUAJIT_INC" ${{targets.destdir}}/usr/local/include/lua

subpackages:
  - name: luajit-dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - luajit
    description: luajit dev

update:
  enabled: false # package uses special versioning
