package:
  name: mimalloc
  version: 1.7.6
  epoch: 0
  description: "A compact general purpose allocator with excellent performance"
  copyright:
    - license: MIT
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/microsoft/mimalloc/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: d74f86ada2329016068bc5a243268f1f555edd620b6a7d6ce89295e7d6cf18da
      strip-components: 1

  - name: 'Configure mimalloc'
    runs: |
      cmake .

  - uses: autoconf/make

  - uses: autoconf/make-install

subpackages:
  - name: "mimalloc-dev"
    description: "headers for mimalloc2"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - mimalloc

update:
  enabled: false
