package:
  name: modsecurity
  version: 3.0.5
  epoch: 0
  description: "ModSecurity is an open source, cross platform web application firewall (WAF) engine"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle
      - git
      - cmake
      - autoconf
      - automake
      - pkgconf
      - make
      - libtool
      - curl
      - curl-dev
      - libxml2
      - pcre
      - pcre-dev
      - linux-headers
      - luajit

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SpiderLabs/ModSecurity
      expected-commit: bf881a4eda343d37629e39ede5e28b70dc4067c0
      tag: v${{package.version}}

  - name: 'Configure MODSECURITY'
    runs: |
      git submodule init
      git submodule update

      sh build.sh

      # https://github.com/SpiderLabs/ModSecurity/issues/1909#issuecomment-465926762
      sed -i '115i LUA_CFLAGS="${LUA_CFLAGS} -DWITH_LUA_JIT_2_1"' build/lua.m4
      sed -i '117i AC_SUBST(LUA_CFLAGS)' build/lua.m4
      ./configure \
      --disable-doxygen-doc \
      --disable-doxygen-html \
      --disable-examples

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: false
