package:
  name: msgpack
  version: 3.3.0
  epoch: 0
  description: "msgpack for C/C++."
  copyright:
    - license: BSL-1.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/msgpack/msgpack-c/archive/cpp-${{package.version}}.tar.gz
      expected-sha256: 754c3ace499a63e45b77ef4bcab4ee602c2c414f58403bce826b76ffc2f77d0b
      strip-components: 1

  - name: 'Configure MSGPACK'
    runs: |
      cmake -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=OFF \
      -DMSGPACK_BUILD_EXAMPLES=OFF \
      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true .

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: false
