package:
  name: opentracing
  version: 0.0_git20210423
  epoch: 0
  description: "C++ implementation of the OpenTracing API http://opentracing.io"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - build-base
      - ca-certificates-bundle
      - cmake

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/opentracing/opentracing-cpp/archive/f86b33f3d9e7322b1298ba62d5ffa7a9519c4c41.tar.gz
      expected-sha256: cbe625cba85291712253db5bc3870d60c709acfad9a8af5a302673d3d201e3ea
      strip-components: 1

  - name: 'Configure OPENTRACING CPP'
    runs: |
      cmake -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_TESTING=OFF \
      -DBUILD_SHARED_LIBS=OFF \
      -DBUILD_MOCKTRACER=OFF \
      -DBUILD_STATIC_LIBS=ON \
      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true \
      .

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: false
