package:
  name: ssdeep
  version: 2.14.1
  epoch: 0
  description: "Fuzzy hashing API and fuzzy hashing tool"
  copyright:
    - license: GPL-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-baselayout
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - autoconf
      - pkgconf
      - make
      - automake
      - libtool

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/ssdeep-project/ssdeep/archive/refs/tags/release-${{package.version}}.tar.gz
      expected-sha256: d96f667a8427ad96da197884574c7ca8c7518a37d9ac8593b6ea77e7945720a4
      strip-components: 1

  - name: 'Configure SSDEEP'
    runs: |
      ./bootstrap
      ./configure

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: false
