package:
  name: yaml-cpp
  version: 0.7.0
  epoch: 0
  description: "yaml-cpp is a YAML parser and emitter in C++ matching the YAML 1.2 spec."
  copyright:
    - license: MIT
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/jbeder/yaml-cpp/archive/yaml-cpp-${{package.version}}.tar.gz
      expected-sha256: 43e6a9fcb146ad871515f0d0873947e5d497a1c9c60c58cb102a97b47208b7c3
      strip-components: 1

  - uses: cmake/configure
    with:
      opts: |
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true \
        -DYAML_BUILD_SHARED_LIBS=ON \
        -DYAML_CPP_BUILD_TESTS=OFF \
        -DYAML_CPP_BUILD_TOOLS=OFF

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: "yaml-cpp-dev"
    description: "headers for yaml-cpp"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - yaml-cpp

update:
  enabled: false
