package:
  name: zipkin-cpp
  version: 0.0_git20210228
  epoch: 0
  description: "OpenTracing implementation for Zipkin in C++."
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - cmake
      - curl
      - curl-dev
      - opentracing-cpp

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/rnburn/zipkin-cpp-opentracing/archive/f69593138ff84ca2f6bc115992e18ca3d35f344a.tar.gz
      expected-sha256: 71de3d0658935db7ccea20e006b35e58ddc7e4c18878b9523f2addc2371e9270
      strip-components: 1

  - name: 'Configure ZIPKIN CPP VERSION'
    runs: |
      cat <<EOF > export.map
      {
        global:
          OpenTracingMakeTracerFactory;
          local: *;
      };
      EOF

      cmake -DCMAKE_BUILD_TYPE=Release \
      -DBUILD_SHARED_LIBS=OFF \
      -DBUILD_PLUGIN=ON \
      -DBUILD_TESTING=OFF \
      -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=true .

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: false
