package:
  name: py3-yaml
  version: 6.0
  epoch: 0
  description: "Python3 bindings for YAML"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - python3-dev
      - py3-setuptools
      - yaml-dev
      - cython
      
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/yaml/pyyaml/archive/${{package.version}}.tar.gz
      expected-sha256: f33eaba25d8e0c1a959bbf00655198c287dfc5868f5b7b01e401eaa1796cc778
# without --with-libyaml for now
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
