package:
  name: py3-docutils
  version: 0.19
  epoch: 3
  description: "Documentation Utilities for Python3"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-2-Clause AND GPL-3.0-or-later AND Python-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/d/docutils/docutils-${{package.version}}.tar.gz
      expected-sha256: 33995a6753c30b7f577febfc2c50411fec6aac7f7ffeb7c4cfe5991072dcf9e6
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --skip-build --root="${{targets.destdir}}"
      # Remove .py extension and add version suffix to executable files.
      for path in "${{targets.destdir}}"/usr/bin/*.py; do
        mv "$path" "${path/.py/}"
        ln -sfv "$(basename "${path/.py/}")" "$path"
        ln -sfv "$(basename "${path/.py/}")" "${path/.py/}-3"
      done
  - uses: strip
