package:
  name: py3-packaging
  version: 21.3
  epoch: 3
  description: "core utilities for python3 packaging"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Apache-2.0 AND BSD-2-Clause
  dependencies:
    runtime:
      - python3
      - py3-parsing

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-parsing

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/packaging/packaging-${{package.version}}.tar.gz
      expected-sha256: dd47c42927d89ab911e606518907cc2d3a1f38bbd026385970643f9c5b8ecfeb
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
