package:
  name: py3-tomli
  version: 2.0.1
  epoch: 2
  description: "TOML parser"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-installer

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/t/tomli/tomli-${{package.version}}-py3-none-any.whl
      expected-sha256: 939de3e7a6161af0c887ef91b7d41a53e7c5a1ca976325f429cb46ea9bc30ecc
      extract: false
  - runs: |
      python3 -m installer -d "${{targets.destdir}}" tomli-${{package.version}}-py3-none-any.whl
  - uses: strip
