package:
  name: py3-s3transfer
  version: 0.5.1
  epoch: 0
  description: "Amazon S3 Transfer Manager for Python"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-botocore

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/boto/s3transfer/archive/${{package.version}}.tar.gz
      expected-sha256: 3caa96971aca147a8d7b2becef668b78601110ac8672f227556ec990801d2fea
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
