package:
  name: py3-flit-core
  version: 3.8.0
  epoch: 3
  description: "simple packaging tool for simple packages (core)"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause
  dependencies:
    runtime:
      - python3
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-installer
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/f/flit/flit-${{package.version}}.tar.gz
      expected-sha256: d0f2a8f4bd45dc794befbf5839ecc0fd3830d65a57bd52b5997542fac5d5e937
  - runs: |
      cd flit_core
      python3 build_dists.py
  - runs: |
      cd flit_core
      python3 -m installer -d "${{targets.destdir}}" dist/flit_core-${{package.version}}-py3-none-any.whl
  - runs: |
      rm -rf "${{targets.destdir}}"/usr/lib/python3*/site-packages/flit_core/tests
  - uses: strip
