package:
  name: py3-contextlib2
  version: 21.6.0
  epoch: 2
  description: "backports of the contextlib module from newer versions of python"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: PSF-2.0 AND Apache-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/c/contextlib2/contextlib2-${{package.version}}.tar.gz
      expected-sha256: ab1e2bfe1d01d968e1b7e8d9023bc51ef3509bba217bb730cee3827e1ee82869
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
