package:
  name: py3-parsing
  version: 3.0.9
  epoch: 3
  description: "simple packaging tool for simple packages (core)"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-installer
      - py3-flit-core
      - py3-gpep517

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pyparsing/pyparsing-${{package.version}}.tar.gz
      expected-sha256: 2b020ecf7d21b687f219b71ecad3631f644a47f01403fa1d1036b0c6416d70fb
  - runs: |
      mkdir -p dist
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1
  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/pyparsing-${{package.version}}-py3-none-any.whl
  - uses: strip
