package:
  name: py3-pep517
  version: 0.13.0
  epoch: 2
  description: "wrappers to build python3 packages with PEP 517 hooks"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3
      - py3-tomli

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-installer
      - py3-flit-core
      - py3-gpep517

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pep517/pep517-${{package.version}}.tar.gz
      expected-sha256: ae69927c5c172be1add9203726d4b84cf3ebad1edcd5f71fcdc746e66e829f59
  - runs: |
      mkdir -p dist
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1
  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/pep517-${{package.version}}-py3-none-any.whl
  - uses: strip
