package:
  name: py3-pluggy
  version: 1.0.0
  epoch: 0
  description: "Plugin management and hook calling for Python"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools
      
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pluggy/pluggy-${{package.version}}.tar.gz
      expected-sha512: cf0bcbb4330c24ce473614befa19548f33fb39fa0ad094e1eae786202d7adadc28e16499f80ab96b630091765404ca5c5b6f9a55bc605e03514d8ab50cf9ae00
  - uses: patch
    with:
      patches: 001-eliminate-setuptools_scm.patch
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
