package:
  name: py3-dateutil
  version: 2.8.2
  epoch: 1
  description: "Python3 extensions for datetime module"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Apache-2.0 AND BSD-3-Clause
  dependencies:
    runtime:
      - python3
      - py3-six

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools
      - py3-gpep517
      
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/python-dateutil/python-dateutil-${{package.version}}.tar.gz
      expected-sha256: 0123cacc1627ae19ddf3c27a5de5bd67ee4586fbdd6440d9748f8abb483d3e86
  - runs: |
      # Generate _version.py ourselves since we don't use setuptools_scm
      # TODO (tuananh): hardcode the version tuple for now
      cat <<- EOF >dateutil/_version.py
      # coding: utf-8
      version = '${{package.version}}'
      version_tuple = (2,8,2)
      EOF

      sed -e '/setuptools_scm/d' -i setup.cfg
      sed -e "s/setup(/setup(\n      version='${{package.version}}',/" -i setup.py
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
