package:
  name: py3-botocore
  version: 1.21.49
  epoch: 0
  description: "The low-level, core functionality of Boto3"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-dateutil
      - py3-docutils
      - py3-jmespath
      - py3-urllib3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/b/botocore/botocore-${{package.version}}.tar.gz
      expected-sha256: 0161c3b64e34315928aae7fdbce49e684c9c2cfad2435cb22023b7ad87306f12
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
