package:
  name: py3-rsa
  version: 4.9
  epoch: 0
  description: "Pure-Python3 RSA implementation"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-asn1

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/r/rsa/rsa-${{package.version}}.tar.gz
      expected-sha256: e38464a49c6c85d7f1351b0126661487a7e0a14a50f1675ec50eb34d4f20ef21
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
