package:
  name: py3-sphinx
  version: 6.0.0
  epoch: 0
  description: "Python Documentation Generator"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-gpep517
      - py3-flit-core
      - py3-installer

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/sphinx-doc/sphinx/archive/v${{package.version}}.tar.gz
      expected-sha512: 6efcbe57170cacec6f3c7f11f09094d096dc2afb7e0470c7cbdb9ea209dcbb782a6227a32de41974258555fa01986406a6564587f6b414594c452dcc6b8a06fc
  - runs: |
      mkdir -p dist
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1
  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinx-*.whl
  - uses: strip
