package:
  name: py3-appdirs
  version: 1.4.4
  epoch: 3
  description: "a small python module for appdir support"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/a/appdirs/appdirs-${{package.version}}.tar.gz
      expected-sha256: 7d5d0167b2b1ba821647616af46a749d1c653740dd0d2415100fe26e27afdf41
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
