package:
  name: py3-jinja2
  version: 3.1.2
  epoch: 2
  description: "A small but fast and easy to use stand-alone python template engine"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: BSD-3-Clause
  dependencies:
    runtime:
      - py3-markupsafe

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3-dev
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/J/Jinja2/Jinja2-3.1.2.tar.gz
      expected-sha512: 5dfe122c1beef5305b34d25f22f96607bd3a6cba098b03091850ea36fefe62b645a7218d7584b35bea252393ac922c9bb3654a9e90f23bcfb273e811fcf2f2c1
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"

      docdir="/usr/share/doc/${{package.name}}"
      # Note: The documentation in the docs directory needs to be generated
      # by py-sphinx, however, this package (py-jinja2) is a dependency of
      # Sphinx itself!
      mkdir -p "$docdir"
      cp -R docs examples "$docdir"/

      install -m 644 -D LICENSE.rst /usr/share/licenses/${{package.name}}/LICENSE.rst
  - uses: strip
