package:
  name: py3-pygments
  version: 2.14.0
  epoch: 2
  description: Syntax highlighting package written in Python
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-2-Clause
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - py3-setuptools
      - python3
pipeline:
  - uses: fetch
    with:
      expected-sha256: b3ed06a9e8ac9a9aae5a6f5dbe78a8a58655d17b43b93c078f094ddc476ae297
      uri: https://files.pythonhosted.org/packages/source/P/Pygments/Pygments-${{package.version}}.tar.gz
  - runs: python3 setup.py build
  - runs: |
      python3 setup.py install --skip-build --root=${{targets.destdir}}

      mkdir -p ${{targets.destdir}}/usr/bin
      ln -s pygmentize ${{targets.destdir}}/usr/bin/pygmentize-3
subpackages:
  - name: py3-pygments-doc
    pipeline:
      - runs: |
          destdir=${{targets.subpkgdir}}/usr/share/doc/py3-pygments

          cd "$builddir"

          install -m 644 -D doc/pygmentize.1 \
            ${{targets.subpkgdir}}/usr/share/man/man1/pygmentize.1

          mkdir -p "$destdir"
          cp AUTHORS CHANGES LICENSE "$destdir"/

          # Note: The documentation in the doc directory needs to be generated
          # by py-sphinx
          cp -R ./doc/docs/* "$destdir"/
      - uses: split/manpages
    description: py3-pygments manpages
