package:
  name: py3-urllib3
  version: 1.26.13
  epoch: 0
  description: "HTTP library with thread-safe connection pooling, file post, and more"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools
      
pipeline:
  - uses: fetch
    with:
      uri: https://github.com/urllib3/urllib3/releases/download/${{package.version}}/urllib3-${{package.version}}.tar.gz
      expected-sha256: c083dd0dce68dbfbe1129d5271cb90f9447dea7d52097c6e0126120c521ddea8
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
