package:
  name: py3-pathspec
  version: 0.10.3
  epoch: 0
  description: "Utility library for gitignore style pattern matching of file paths"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MPL-2.0
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-setuptools
      
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/p/pathspec/pathspec-${{package.version}}.tar.gz
      expected-sha512: d0876374ab20d3624f1ba522de30472e401220ef3b269df9ea2e20526d5abddb8fd19866b0e3405a4746beb3a4b4b6f21ada4da5b7292a46febd6d418829e0f3
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build 
  - uses: strip
