package:
  name: py3-retrying
  version: 1.3.4
  epoch: 2
  description: "python 2 and 3 compatibility library"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:
      - python3
      - py3-six
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-six
      - py3-setuptools
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/r/retrying/retrying-${{package.version}}.tar.gz
      expected-sha256: 345da8c5765bd982b1d1915deb9102fd3d1f7ad16bd84a9700b85f64d24e8f3e
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
