package:
  name: py3-markupsafe
  version: 2.1.2
  epoch: 2
  description: "Implements a XML/HTML/XHTML Markup safe string"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause
  dependencies:
    runtime:
      - python3
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3-dev
      - py3-setuptools
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/M/MarkupSafe/MarkupSafe-${{package.version}}.tar.gz
      expected-sha512: 84dbeddaf2df713b3cce94eb64876fea8f80c608e25130c18e4691be2b1dea56df8b772d26c0caca88231ef795125eb9678210c33bf20518c18e3047912ddb4b
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
