package:
  name: py3-six
  version: 1.16.0
  epoch: 3
  description: "python 2 and 3 compatibility library"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/s/six/six-${{package.version}}.tar.gz
      expected-sha256: 1e61c37477a1626458e36f7b1d82aa5c9b094fa4802892072e49de9c60c4c926
  - runs: |
      python3 setup.py build
  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
