package:
  name: py3-setuptools
  # NOTE: Be very careful when upgrading this package as upstream
  # aggressively deprecates functionality used by packages in
  # production.
  version: 59.4.0
  epoch: 4
  description: "collection of enhancements to the python3 distutils"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3
      - py3-appdirs
      - py3-more-itertools
      - py3-ordered-set
      - py3-packaging
      - py3-parsing

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-appdirs
      - py3-more-itertools
      - py3-ordered-set
      - py3-packaging
      - py3-parsing
      - py3-setuptools

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-${{package.version}}.tar.gz
      expected-sha256: b4c634615a0cf5b02cf83c7bedffc8da0ca439f00e79452699454da6fbd4153d
  - uses: patch
    with:
      patches: CVE-2022-40897.patch
  - name: "Unbundle vendored dependencies"
    runs: |
      rm -rf pkg_resources/extern pkg_resources/_vendor \
        setuptools/extern setuptools/_vendor

      for _module in setuptools pkg_resources '' ; do
        find . -name \*.py -exec sed -i \
          -e 's/from '$_module.extern' import/import/' \
          -e 's/from '$_module.extern'./from /' \
          -e 's/import '$_module.extern'./import /' \
          -e "s/__import__('$_module.extern./__import__('/" \
          {} +
      done

      sed -e '/tag_build = .post/d' \
          -e '/tag_date = 1/d' \
          -i setup.cfg
  - runs: |
      python3 setup.py build
  - runs: |
      mkdir -p build/scripts-3.11
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build
  - uses: strip

advisories:
  CVE-2022-40897:
    - timestamp: 2023-02-20T14:52:10.705767-05:00
      status: fixed
      fixed-version: 59.4.0-r4

secfixes:
  59.4.0-r4:
    - CVE-2022-40897
