package:
  name: py3-more-itertools
  version: 9.0.0
  epoch: 3
  description: "more routines for operating on iterables, beyond itertools"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3
environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-installer
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/m/more_itertools/more_itertools-${{package.version}}-py3-none-any.whl
      expected-sha256: 250e83d7e81d0c87ca6bd942e6aeab8cc9daa6096d12c5308f3f92fa5e5c1f41
      extract: false
  - runs: |
      python3 -m installer -d "${{targets.destdir}}" more_itertools-${{package.version}}-py3-none-any.whl
  - uses: strip
