package:
  name: py3-hatchling
  version: 1.11.1
  epoch: 0
  description: "Modern, extensible Python build backend"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-installer
      
pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/py3/h/hatchling/hatchling-${{package.version}}-py3-none-any.whl
      expected-sha512: 7f45fb0e20c4a7769c12dc58805cd91ffb50de35f314eade923212ccb9c8de9f0b38ef5f1ba9098e089a7db1e770dc3b0602e264dcbc6d2c0fd41cb3ae27ce21
      extract: false
  - runs: |
      python3 -m installer -d "${{targets.destdir}}" ./hatchling-${{package.version}}-py3-none-any.whl
  - uses: strip
