package:
  name: py3-setuptools-stage0
  version: 52.0.0
  epoch: 2
  description: "collection of enhancements to the python3 distutils"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - python3
      - py3-appdirs
      - py3-more-itertools
      - py3-ordered-set
      - py3-packaging
      - py3-parsing
    provides:
      - py3-setuptools=52.0.0-r0

environment:
  contents:
    packages:
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - python3
      - py3-appdirs
      - py3-more-itertools
      - py3-ordered-set
      - py3-packaging
      - py3-parsing

pipeline:
  - uses: fetch
    with:
      uri: https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-${{package.version}}.tar.gz
      expected-sha256: fb3a1ee622509550dbf1d419f241296169d7f09cb1eb5b1736f2f10965932b96
  - name: "Unbundle vendored dependencies"
    runs: |
      rm -rf pkg_resources/extern pkg_resources/_vendor \
        setuptools/extern setuptools/_vendor

      for _module in setuptools pkg_resources '' ; do
        find . -name \*.py -exec sed -i \
          -e 's/from '$_module.extern' import/import/' \
          -e 's/from '$_module.extern'./from /' \
          -e 's/import '$_module.extern'./import /' \
          -e "s/__import__('$_module.extern./__import__('/" \
          {} +
      done

      sed -e '/tag_build = .post/d' \
          -e '/tag_date = 1/d' \
          -i setup.cfg

      python3 bootstrap.py
  - runs: |
      python3 setup.py build
  - runs: |
      mkdir -p build/scripts-3.10
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}"
  - uses: strip
