package:
  name: python-3.11
  version: 3.11.1
  epoch: 5
  description: "the Python programming language"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: PSF-2.0
  dependencies:
    provides:
      - python3=3.11.999
secfixes:
  3.0.7-r0:
    - CVE-2020-10735
environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/bootstrap/stage3
    keyring:
      - https://packages.wolfi.dev/bootstrap/stage3/wolfi-signing.rsa.pub
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev
pipeline:
  - uses: fetch
    with:
      uri: https://www.python.org/ftp/python/${{package.version}}/Python-${{package.version}}.tar.xz
      expected-sha256: 85879192f2cffd56cb16c092905949ebf3e5e394b7f764723529637901dfb58f
  - name: Force use of system libraries
    runs: |
      rm -rf Modules/expat \
        Modules/_ctypes/darwin* \
        Modules/_ctypes/libffi*
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip \
         --with-lto
  - uses: autoconf/make
  - uses: autoconf/make-install
  - runs: |
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyc' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name '*.pyo' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type f -name 'libpython*.a' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'test' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'tests' -exec rm -rf '{}' +
      find ${{targets.destdir}}/usr/lib -type d -name 'idle_test' -exec rm -rf '{}' +
  - name: Install python symlink
    runs: |
      ln -s python3 "${{targets.destdir}}"/usr/bin/python
  - uses: strip
subpackages:
  - name: "python-3.11-doc"
    description: "python3 documentation"
    pipeline:
      - uses: split/manpages
  - name: "python-3.11-dev"
    description: "python3 development headers"
    pipeline:
      - uses: split/dev
      # pyconfig.h is needed at runtime... ugh.
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/include/python3.11
          mv "${{targets.subpkgdir}}"/usr/include/python3.11/pyconfig.h "${{targets.destdir}}"/usr/include/python3.11
    dependencies:
      runtime:
        - python3
      provides:
        - python3-dev=3.11.999
advisories:
  CVE-2020-10735:
    - timestamp: 2022-09-12T21:06:30+00:00
      status: fixed
      fixed-version: 3.0.7-r0
