package:
  name: ruby3.2-protocol-http
  version: 0.24.1
  epoch: 0
  description: Provides abstractions to handle HTTP protocols.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: protocol-http

pipeline:
  - uses: fetch
    with:
      expected-sha256: bdb3d52ded81abd86202952119afe0db38957f8070db0e46f6bdb3fbed300500
      uri: https://github.com/socketry/protocol-http/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
