package:
  name: ruby3.2-serverengine
  version: 2.3.1
  epoch: 0
  description: A framework to implement robust multiprocess servers like Unicorn
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: Apache 2.0
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: serverengine

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      repository: https://github.com/fluent/serverengine.git
      tag: v${{package.version}}
      expected-commit: c35e3a523958a82b6e27580f8197d66e601a0092
      destination: ${{vars.gem}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
