package:
  name: ruby3.2-tzinfo-data
  version: 1.2022.7
  epoch: 0
  description: TZInfo::Data contains data from the IANA Time Zone database packaged as Ruby modules for use with TZInfo.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: tzinfo-data

pipeline:
  - uses: fetch
    with:
      expected-sha256: ad7e2b25b5eedd45aeb695a197ad6372355e839f38abdaf2b66f5934618fd262
      uri: https://github.com/tzinfo/tzinfo-data/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
