package:
  name: ruby3.2-async-io
  version: 1.34.3
  epoch: 0
  description: Provides support for asynchonous TCP, UDP, UNIX and SSL sockets.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: async-io

pipeline:
  - uses: fetch
    with:
      expected-sha256: fa6098544a8eb35b3c64618c1a2510a2d09df449493d3cd9453187df479b58cb
      uri: https://github.com/socketry/async-io/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
