package:
  name: ruby3.2-protocol-hpack
  version: 1.4.2
  epoch: 0
  description: A compresssor and decompressor for HTTP 2.0 HPACK.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: protocol-hpack

  # NOTE: http-hpack is required for the gemspec name. It has since been
  # updated to match the standard naming scheme, however it is not in this tag
  gemspec: http-hpack

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      repository: https://github.com/socketry/http-hpack.git
      tag: v${{package.version}}
      expected-commit: 031b055eeea20f42facd65e1b57e6d8af93292f3
      destination: ${{vars.gem}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          # NOTE: See vars.gemspec comment for details
          gem: ${{vars.gemspec}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
