package:
  name: ruby3.2-protocol-http1
  version: 0.15.0
  epoch: 0
  description: A low level implementation of the HTTP/1 protocol.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: protocol-http1

pipeline:
  - uses: fetch
    with:
      expected-sha256: cdb044d2fb8daa9bd85f65fb209aec09e032804cf211d7d2257c1d423e152751
      uri: https://github.com/socketry/protocol-http1/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
