package:
  name: ruby3.2-sigdump
  version: 0.2.4
  epoch: 0
  description: Setup signal handler which dumps backtrace of running threads and number of allocated objects per class. Require 'sigdump/setup', send SIGCONT, and see /tmp/sigdump-&lt;pid&gt;.log.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: sigdump

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      repository: https://github.com/frsyuki/sigdump.git
      tag: v${{package.version}}
      expected-commit: 57570f04456560512e4efc1c6fa695b76c17dc0d
      destination: ${{vars.gem}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
