package:
  name: ruby3.2-console
  version: 1.16.2
  epoch: 0
  description: Beautiful logging for Ruby.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: console

pipeline:
  - uses: fetch
    with:
      expected-sha256: 8df6857a79b7c75325947c0b273c1c38511e9f36806437b8b8d4213594696421
      uri: https://github.com/socketry/console/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
