package:
  name: ruby3.2-rexml
  version: 3.2.5
  epoch: 0
  description: An XML toolkit for Ruby
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: rexml

pipeline:
  - uses: fetch
    with:
      expected-sha256: 23b7a82bf41bcd1201f67e7ca6e795eee1bb76dce94cd7abf411969e39c5c71d
      uri: https://github.com/ruby/rexml/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
