package:
  name: ruby3.2-async-http
  version: 0.60.1
  epoch: 0
  description: A HTTP client and server library.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: async-http

pipeline:
  - uses: fetch
    with:
      expected-sha256: c8d548adcdc022ade0c76c8c7a583e61c7b837a4fb42bf5c2b0957962e8ebac6
      uri: https://github.com/socketry/async-http/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
