package:
  name: ruby3.2-concurrent-ruby
  version: 1.2.0
  epoch: 0
  description: Modern concurrency tools including agents, futures, promises, thread pools, actors, supervisors, and more. Inspired by Erlang, Clojure, Go, JavaScript, actors, and classic concurrency patterns.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: ""
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: concurrent-ruby

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      repository: https://github.com/ruby-concurrency/concurrent-ruby.git
      tag: v${{package.version}}
      expected-commit: cdbc6db6c7530eb64ecfb7417fb7a449c7ec2fd6
      destination: ${{vars.gem}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: patch
        with:
          # Since we're inside the working-directory, the patch will be
          # in the previous directory
          patches: ../001-disable-java.patch
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
