package:
  name: ruby3.2-async-pool
  version: 0.3.12
  epoch: 0
  description: A singleplex and multiplex resource pool for implementing robust clients.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: async-pool

pipeline:
  - uses: fetch
    with:
      expected-sha256: 0b708ff0f8de392dd674be9725ab4a94595b13b0a4ed50fd81dc2e4a328ec072
      uri: https://github.com/socketry/async-pool/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
