package:
  name: ruby3.2-webrick
  version: 1.7.0
  epoch: 0
  description: WEBrick is an HTTP server toolkit that can be configured as an HTTPS server, a proxy server, and a virtual-host server.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: Ruby
    - paths:
        - '*'
      attestation: TODO
      license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: webrick

pipeline:
  - uses: fetch
    with:
      expected-sha256: 25df35c696301deddec8cc929954284fa3dfaa86ad90c0cce2ecc5740c476545
      uri: https://github.com/ruby/webrick/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
