package:
  name: ruby3.2-protocol-http2
  version: 0.15.1
  epoch: 0
  description: A low level implementation of the HTTP/2 protocol.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: protocol-http2

pipeline:
  - uses: fetch
    with:
      expected-sha256: 73572decaf977081bc723075faa96f9c3276e8ffa5baf02526e0401e7975d5b2
      uri: https://github.com/socketry/protocol-http2/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
