package:
  name: ruby3.2-timers
  version: 4.3.5
  epoch: 0
  description: Pure Ruby one-shot and periodic timers.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: timers

pipeline:
  - uses: fetch
    with:
      expected-sha256: 413d3c424f8b83ffbd022bd0324eb453c2d8416b6992d74f2a64c65c5ae749fb
      uri: https://github.com/socketry/timers/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
