package:
  name: ruby3.2-strptime
  version: 0.2.5
  epoch: 0
  description: a fast strptime/strftime engine which uses VM.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: strptime

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      repository: https://github.com/nurse/strptime.git
      tag: v${{package.version}}
      expected-commit: 1583aaa510cae4660907b22c8262ab31b1eb1864
      destination: ${{vars.gem}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
