package:
  name: ruby3.2-io-event
  version: 1.1.6
  epoch: 0
  description: An event loop.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: io-event

pipeline:
  - uses: fetch
    with:
      expected-sha256: 87d2432ce03f9a2f6fcfe148375764a9c27791e8c229d17db7de6d71fce47085
      uri: https://github.com/socketry/io-event/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
