package:
  name: ruby3.2-fluentd
  version: 1.15.3
  epoch: 1
  description: Fluentd is an open source data collector designed to scale and simplify log management. It can collect, process and ship many kinds of data in near real-time.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: Apache-2.0
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: fluentd

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      repository: https://github.com/fluent/fluentd.git
      tag: v${{package.version}}
      expected-commit: e89092ce1132a933c12bb23fe8c9323c07ca81f5
      destination: ${{vars.gem}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}

  - uses: ruby/clean
  - runs: |-
      GEM_DIR=${{targets.destdir}}$(ruby -e 'puts Gem.default_dir')/gems/${{vars.gem}}-${{package.version}}
      rm -rf ${GEM_DIR}/test \
             ${GEM_DIR}/docs \
             ${GEM_DIR}/*.md \
             ${GEM_DIR}/.github
