package:
  name: ruby3.2-tzinfo
  version: 2.0.6
  epoch: 0
  description: TZInfo provides access to time zone data and allows times to be converted using time zone rules.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: tzinfo

pipeline:
  - uses: fetch
    with:
      expected-sha256: dfbf1dbe06d1646ed36ac740e50f27ebb76c5b7f85205918813dc60246cee655
      uri: https://github.com/tzinfo/tzinfo/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
