package:
  name: ruby-3.0
  version: 3.0.4
  epoch: 3
  description: "the Ruby programming language"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: PSF-2.0
  dependencies:
    runtime:

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bzip2-dev
      - expat-dev
      - gdbm-dev
      - libffi-dev
      - linux-headers
      - mpdecimal-dev
      - ncurses-dev
      - openssl-dev
      - readline-dev
      - sqlite-dev
      - xz-dev
      - zlib-dev
      - oniguruma-dev

pipeline:
  - uses: fetch
    with:
      uri: https://cache.ruby-lang.org/pub/ruby/3.0/ruby-${{package.version}}.tar.gz
      expected-sha256: 70b47c207af04bce9acea262308fb42893d3e244f39a4abc586920a1c723722b
  - name: Configure
    runs: |
      ./configure \
         --host=${{host.triplet.gnu}} \
         --build=${{host.triplet.gnu}} \
         --target=${{host.triplet.gnu}} \
         --prefix=/usr \
         --enable-ipv6 \
         --enable-loadable-sqlite-extensions \
         --enable-optimizations \
         --enable-shared \
         --without-lto \
         --with-computed-gotos \
         --with-dbmliborder=gdbm:ndbm \
         --with-system-expat \
         --with-system-ffi \
         --with-system-libmpdec \
         --without-ensurepip
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: "ruby-3.0-doc"
    description: "ruby documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/
          mv "${{targets.destdir}}"/usr/share/ri "${{targets.subpkgdir}}"/usr/share/

  - name: "ruby-3.0-dev"
    description: "ruby development headers"
    pipeline:
      - uses: split/dev
