package:
  name: ruby3.2-traces
  version: 0.8.0
  epoch: 0
  description: Application instrumentation and tracing.
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: traces

pipeline:
  - uses: fetch
    with:
      expected-sha256: d1123d125c159e20921d11d364fd0ac62b488f0a9f7ea79e0ca75958002d95a8
      uri: https://github.com/socketry/traces/archive/refs/tags/v${{package.version}}.tar.gz
  - uses: patch
    with:
      patches: 001-remove-signing-key.patch
  - uses: ruby/build
    with:
      gem: ${{vars.gem}}
  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}
  - uses: ruby/clean
