package:
  name: ruby3.2-yajl-ruby
  version: 1.4.3
  epoch: 0
  description: ruby C bindings for Yajl library
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: ""
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: yajl-ruby

  # The latest releases of yajl-ruby were released on rubygems.org but a tag
  # was not created in the repo itself. https://github.com/brianmario/yajl-ruby
  #
  # This commit matches the 1.4.3 release on rubygems.org so it's used to check
  # the repository out and build the 1.4.3 version of yajl-ruby
  commit: e8de283a6d64f0902740fd09e858fc3d7d803161

pipeline:
  # This package _also_ makes use of `git ls-files` in it's gemspec so the git
  # repo must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      branch: master
      destination: ${{vars.gem}}
      repository: https://github.com/brianmario/yajl-ruby

  - working-directory: ${{vars.gem}}
    pipeline:
      # NOTE: See the vars.commit comment
      - runs: git checkout ${{vars.commit}}
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
