package:
  name: ruby3.2-bundler
  version: 2.4.7
  epoch: 1
  description: "Manage an application's gem dependencies"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - build-base
      - busybox
      - bash
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: bundler

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/rubygems/rubygems/archive/bundler-v${{package.version}}.tar.gz
      expected-sha256: 78b91bb1dee3814e9de8e3a6d80619d599ed024cfe02eed9c66679851d808f45
  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
      - name: build-docs-clean
        runs: |
          export INSTALL_DIR=${{targets.destdir}}/$(ruby -e 'puts Gem.default_dir')
          for n in 1 5; do
            mkdir -p "${{targets.destdir}}"/usr/share/man/man$n
            mv "$INSTALL_DIR"/gems/bundler-${{package.version}}/lib/bundler/man/*.$n "${{targets.destdir}}"/usr/share/man/man$n/
          done

          rm -rf "$INSTALL_DIR"/cache \
                 "$INSTALL_DIR"/build_info \
                 "$INSTALL_DIR"/doc \
                 "$INSTALL_DIR"/gems/bundler-${{package.version}}/man \
                 "$INSTALL_DIR"/gems/bundler-${{package.version}}/*.md

subpackages:
  - name: "ruby3.2-bundler-doc"
    description: "ruby-bundler documentation"
    pipeline:
      - uses: split/manpages
