package:
  name: ruby3.2-cool.io
  version: 1.7.1
  epoch: 0
  description: Cool.io provides a high performance event framework for Ruby which uses the libev C library
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: cool.io

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  - uses: git-checkout
    with:
      repository: https://github.com/tarcieri/cool.io.git
      tag: v${{package.version}}
      expected-commit: 8dc015147d40f30f8ee6a5dceae201476bb973a2
      destination: ${{vars.gem}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
