package:
  name: ruby3.2-http_parser.rb
  version: 0.8.0
  epoch: 0
  description: Ruby bindings to https://github.com/joyent/http-parser and https://github.com/http-parser/http-parser.java
  target-architecture:
    - all
  copyright:
    - paths:
        - '*'
      attestation: TODO
      license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - ruby-3.2
      - ruby-3.2-dev
      - build-base
      - busybox
      - git

vars:
  gem: http_parser.rb

pipeline:
  # This package makes use of `git ls-files` in it's gemspec so the git repo
  # must be checked out in order for the gem to build with all files.
  #
  # This package also makes use of git submodules which requires the git repo
  - uses: git-checkout
    with:
      repository: https://github.com/tmm1/http_parser.rb.git
      tag: v${{package.version}}
      expected-commit: 90abe77b061c8b9b76204f53d4c223a2db0c858b
      destination: ${{vars.gem}}

  - working-directory: ${{vars.gem}}
    pipeline:
      - runs: |-
          git submodule init ext/
          git submodule update ext/
      - uses: ruby/build
        with:
          gem: ${{vars.gem}}
      - uses: ruby/install
        with:
          gem: ${{vars.gem}}
          version: ${{package.version}}
      - uses: ruby/clean
