package:
  name: rustls-ffi
  version: 0.8.2
  epoch: 0
  description: "C-to-rustls bindings"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: MIT

environment:
  contents:
    packages:
      - rust
      - libLLVM-15
      - wolfi-base
      - busybox
      - ca-certificates-bundle
      - build-base
      - bash

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/rustls/rustls-ffi/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: aa627cdd1c8183b9c84e2360641dd8efc7412307aa5451b240058c41357d14fd
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip
