package:
  name: rust
  version: 1.67.0
  epoch: 0
  description: "rust a type safe memory safe language"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: Apache-2.0 AND MIT
  dependencies:
    runtime:
      - libLLVM-15
    provides: 
    # hack to allow rust to bootstrap itself
      - rust-bootstrap=1.67.0
      
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - libgit2-dev
      - coreutils
      - curl-dev
      - file
      - libssh2-dev
      - llvm15
      - libLLVM-15
      - llvm15-dev
      - clang-15
      - openssl-dev
      - python3
      - wasi-libc
      - xz-dev
      - zlib-dev
      - patch
      - rust
      # During bootstrapping, this must depend on rust-stage0, which builds a Rust
      # package using a prebuilt Rust toolchain provided by the Rust team.
      # After bootstrapping, rust can depend on a previously built Rust toolchain.
      # - rust-stage0
pipeline:
  - uses: fetch
    with:
      uri: https://static.rust-lang.org/dist/rustc-${{package.version}}-src.tar.xz
      expected-sha256: 9ef8cf88a1d35d319808daf2f193aadca9ed9bcae1d4d5db8946a448c9432c6d
      extract: false 
  - runs: |
      tar -xJf rustc-${{package.version}}-src.tar.xz
      rm rustc-${{package.version}}-src.tar.xz
  - runs: |
      export CFLAGS="$CFLAGS -O2 -I/usr/lib/llvm-15/include"
      export CXXFLAGS="$CXXFLAGS -O2 -I/usr/lib/llvm-15/include"
      export OPENSSL_NO_VENDOR=1
      export RUST_BACKTRACE=1
      export ARCH=${{host.triplet.rust}}
      cd rustc-${{package.version}}-src
      ./configure \
        --host="${ARCH}" \
        --target="${ARCH}" \
        --prefix="/usr" \
        --release-channel="stable" \
        --enable-local-rust \
        --local-rust-root="/usr" \
        --llvm-root="/usr/lib/llvm15" \
        --llvm-config="/usr/bin/llvm-config" \
        --disable-docs \
        --enable-extended \
        --tools="cargo,src" \
        --enable-llvm-link-shared \
        --enable-option-checking \
        --enable-locked-deps \
        --enable-profiler \
        --enable-vendor \
        --dist-compression-formats=gz \
        --python="python3" \
        --set="rust.musl-root=/usr" \
        --set="rust.codegen-units=1" \
        --set="rust.codegen-units-std=1" \
        --set="rust.parallel-compiler=false" \
        --set="target.${ARCH}.musl-root=/usr" \
        --set="target.${ARCH}.crt-static=false" \
        --set="target.${ARCH}.musl-root=/usr" \
        --set="target.${ARCH}.crt-static=false"
  - runs: |
      cd rustc-${{package.version}}-src
      sed 's/#deny-warnings = .*/deny-warnings = false/' -i config.toml
      sed 's|deny(warnings,|deny(|' -i src/bootstrap/lib.rs
      mkdir -p "${{targets.destdir}}/usr"
      unset CARGO_PROFILE_RELEASE_LTO
      unset CARGO_PROFILE_RELEASE_OPT_LEVEL
      unset CARGO_PROFILE_RELEASE_PANIC
      unset CARGO_PROFILE_RELEASE_CODEGEN_UNITS
      export CFLAGS="$CFLAGS -O2 -Iusr/include/llvm15"
      export CXXFLAGS="$CXXFLAGS -O2 -I/usr/include/llvm15"
      export OPENSSL_NO_VENDOR=1
      export RUST_BACKTRACE=1
      DESTDIR=${{targets.destdir}} python3 ./x.py install --jobs ${JOBS:-2}
  - uses: strip
  # delete uneeded files eg uninstalltion
  - runs: |
      rm ${{targets.destdir}}/usr/lib/rustlib/components
      rm ${{targets.destdir}}/usr/lib/rustlib/install.log
      rm ${{targets.destdir}}/usr/lib/rustlib/rust-installer-version
      rm ${{targets.destdir}}/usr/lib/rustlib/uninstall.sh
      rm ${{targets.destdir}}/usr/lib/rustlib/manifest-*
  # rustbuild always installs copies of the shared libraries to /usr/lib,
  # overwrite them with symlinks to the per-architecture versions
  - runs: |
      mkdir -p ${{targets.destdir}}/usr/lib32
      cd ${{targets.destdir}}
      ln -srft usr/lib   usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/*.so
      ln -srft usr/lib32 usr/lib/rustlib/i686-unknown-linux-gnu/lib/*.so
