package:
  name: rust-stage0
  version: 1.65.0
  epoch: 2
  description: "bootstrap package for rust"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: blessing
  dependencies:
    runtime:
    provides:
      - rust=1.65.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: https://static.rust-lang.org/dist/rust-${{package.version}}-x86_64-unknown-linux-gnu.tar.gz
          expected-sha256: 8f754fdd5af783fe9020978c64e414cb45f3ad0a6f44d045219bbf2210ca3cb9
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          uri: https://static.rust-lang.org/dist/rust-${{package.version}}-aarch64-unknown-linux-gnu.tar.gz
          expected-sha256: f406136010e6a1cdce3fb6573506f00d23858af49dd20a46723c3fa5257b7796

  - runs: |
      sh install.sh --verbose --destdir="${{targets.destdir}}" --prefix="/usr"
  - runs: |
      mv "${{targets.destdir}}"/usr/etc "${{targets.destdir}}"/etc
  - uses: strip

subpackages:
  - name: "rust-stage0-doc"
    description: "rust stage0 documentation"
    pipeline:
      - uses: split/manpages
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/

