package:
  name: go-1.19
  version: 1.19.6
  epoch: 1
  description: "the Go programming language"
  target-architecture:
    - all
  copyright:
    - paths:
        - "*"
      attestation: TODO
      license: BSD-3-Clause
  dependencies:
    provides:
      - go=1.19.999
    runtime:
      - build-base
      - bash
      # Needed for cgo linking due to upstream issue #15696 which forces use
      # of the gold linker.
      - binutils-gold
secfixes:
  1.19.3-r0:
    - CVE-2022-41716
  1.19.4-r0:
    - CVE-2022-41717
    - CVE-2022-41720
environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bash
      - go
      # During bootstrapping, this must depend on go-stage0, which builds a Go
      # package using a prebuilt Go toolchain provided by the Go team.
      # After bootstrapping, go can depend on a previously built Go toolchain.
      # - go-stage0
pipeline:
  - uses: fetch
    with:
      uri: https://go.dev/dl/go${{package.version}}.src.tar.gz
      expected-sha256: d7f0013f82e6d7f862cc6cb5c8cdb48eef5f2e239b35baa97e2f1a7466043767
      strip-components: 0
  - runs: |
      cd go/src
      ./make.bash -v
  - runs: |
      cd go

      mkdir -p "${{targets.destdir}}"/usr/bin "${{targets.destdir}}"/usr/lib/go/bin "${{targets.destdir}}"/usr/share/doc/go

      for bin in go gofmt; do
        install -Dm755 bin/$bin "${{targets.destdir}}"/usr/lib/go/bin/$bin
        ln -s /usr/lib/go/bin/$bin "${{targets.destdir}}"/usr/bin/
      done

      cp -a pkg lib "${{targets.destdir}}"/usr/lib/go/
      cp -r doc misc "${{targets.destdir}}"/usr/share/doc/go
      cp -a src "${{targets.destdir}}"/usr/lib/go/

      rm -rf "${{targets.destdir}}"/usr/lib/go/pkg/obj
      rm -rf "${{targets.destdir}}"/usr/lib/go/pkg/bootstrap
      rm -rf "${{targets.destdir}}"/usr/lib/go/pkg/tool/*/api
      rm -rf "${{targets.destdir}}"/usr/lib/go/pkg/*/cmd
      rm -rf "${{targets.destdir}}"/usr/lib/go/pkg/tool/*/api
      rm -rf "${{targets.destdir}}"/usr/lib/go/pkg/tool/*/go_bootstrap
      rm -rf "${{targets.destdir}}"/usr/lib/go/src/cmd/dist/dist

      # Remove tests from /usr/lib/go/src, not needed at runtime
      find "${{targets.destdir}}"/usr/lib/go/src \( -type f -a -name "*_test.go" \) \
        -exec rm -rf \{\} \+
      find "${{targets.destdir}}"/usr/lib/go/src \( -type d -a -name "testdata" \) \
        -exec rm -rf \{\} \+
      find "${{targets.destdir}}"/usr/lib/go/src \( -type f -a -name "*.rc" \) \
        -exec rm -rf \{\} \+
      find "${{targets.destdir}}"/usr/lib/go/src \( -type f -a -name "*.bat" \) \
        -exec rm -rf \{\} \+
  - uses: strip
subpackages:
  - name: "go-1.19-doc"
    description: "go documentation"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/
advisories:
  CVE-2022-41716:
    - timestamp: 2022-11-01T13:39:29-04:00
      status: fixed
      fixed-version: 1.19.3-r0
  CVE-2022-41717:
    - timestamp: 2022-12-07T08:11:39+00:00
      status: fixed
      fixed-version: 1.19.4-r0
  CVE-2022-41720:
    - timestamp: 2022-12-07T08:11:39+00:00
      status: fixed
      fixed-version: 1.19.4-r0
