package:
  name: go-stage0
  version: 1.19.1
  epoch: 2
  description: "bootstrap golang compiler built with Google-provided artifact"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: BSD-3-Clause
  dependencies:
    runtime:
      - build-base
      - bash
    provides:
      - go=1.19-r0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - bash

pipeline:
  - assertions:
      required-steps: 1
    pipeline:
      - if: ${{build.arch}} == 'x86_64'
        uses: fetch
        with:
          uri: https://go.dev/dl/go1.19.1.linux-amd64.tar.gz
          expected-sha256: acc512fbab4f716a8f97a8b3fbaa9ddd39606a28be6c2515ef7c6c6311acffde
          strip-components: 0
      - if: ${{build.arch}} == 'aarch64'
        uses: fetch
        with:
          uri: https://go.dev/dl/go1.19.1.linux-arm64.tar.gz
          expected-sha256: 49960821948b9c6b14041430890eccee58c76b52e2dbaafce971c3c38d43df9f
          strip-components: 0

  # GOROOT cannot be the same as GOROOT_BOOTSTRAP.
  - runs: |
      mv go go1.19.1

  - uses: fetch
    with:
      uri: https://go.dev/dl/go1.19.1.src.tar.gz
      expected-sha256: 27871baa490f3401414ad793fba49086f6c855b1c584385ed7771e1204c7e179
      strip-components: 0

  - runs: |
      cd go/src
      env GOROOT_BOOTSTRAP=/home/build/go1.19.1 ./make.bash -v

  - runs: |
      cd go

      mkdir -p "${{targets.destdir}}"/usr/bin "${{targets.destdir}}"/usr/lib/go/bin "${{targets.destdir}}"/usr/share/doc/go

      for bin in go gofmt; do
        install -Dm755 bin/$bin "${{targets.destdir}}"/usr/lib/go/bin/$bin
        ln -s /usr/lib/go/bin/$bin "${{targets.destdir}}"/usr/bin/
      done

      cp -a pkg lib "${{targets.destdir}}"/usr/lib/go/
      cp -r doc misc "${{targets.destdir}}"/usr/share/doc/go
      cp -a src "${{targets.destdir}}"/usr/lib/go/

      rm -rf "${{targets.destdir}}"/usr/lib/go/pkg/obj
      rm -rf "${{targets.destdir}}"/usr/lib/go/pkg/bootstrap
      rm -f "${{targets.destdir}}"/usr/lib/go/pkg/tool/*/api

      # Remove tests from /usr/lib/go/src, not needed at runtime
      find "${{targets.destdir}}"/usr/lib/go/src \( -type f -a -name "*_test.go" \) \
        -exec rm -rf \{\} \+
      find "${{targets.destdir}}"/usr/lib/go/src \( -type d -a -name "testdata" \) \
        -exec rm -rf \{\} \+
      find "${{targets.destdir}}"/usr/lib/go/src \( -type f -a -name "*.rc" \) \
        -exec rm -rf \{\} \+
      find "${{targets.destdir}}"/usr/lib/go/src \( -type f -a -name "*.bat" \) \
        -exec rm -rf \{\} \+

  - uses: strip

subpackages:
  - name: "go-stage0-doc"
    description: "go stage0 documentation"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share
          mv "${{targets.destdir}}"/usr/share/doc "${{targets.subpkgdir}}"/usr/share/
